[TopIconImage]
    Measure=String
    String=NotepadPlusPlus.png

[TopIconLink]
    Measure=String
    String="C:\Program Files (x86)\Notepad++\notepad++.exe"

[LeftIconImage]
    Measure=String
    String=VSCode.png

[LeftIconLink]
    Measure=String
    String="C:\Users\aaron\AppData\Local\Programs\Microsoft VS Code\Code.exe"

[RightIconImage]
    Measure=String
    String=Gitkraken.png

[RightIconLink]
    Measure=String
    String='C:\Users\aaron\AppData\Local\gitkraken\update.exe "--processStart gitkraken.exe"'