[TopIconImage]
    Measure=String
    String=WoW.png

[TopIconLink]
    Measure=String
    String="C:\Program Files (x86)\World of Warcraft\World of Warcraft Launcher.exe"

[LeftIconImage]
    Measure=String
    String=Hearthstone.png

[LeftIconLink]
    Measure=String
    String="C:\Program Files (x86)\Hearthstone\Hearthstone.exe"

[RightIconImage]
    Measure=String
    String=Factorio.png

[RightIconLink]
    Measure=String
    String="c:\Program Files (x86)\Steam\Steam.exe -applaunch 427520"