[TopIconImage]
    Measure=String
    String=Spotify.png

[TopIconPlayPause]
    Measure=String
    String=Pause.png

[TopIconPlayPauseLink]
    Measure=String
    String='[!CommandMeasure "MeasureMedia" "PlayPause"]'

[TopIconLink]
    Measure=String
    String="C:\Users\aaron\AppData\Roaming\Spotify\Spotify.exe"

[LeftIconImage]
    Measure=String
    String=Previous.png

[RightIconImage]
    Measure=String
    String=Next.png
