[TopIconImage]
    Measure=String
    String=PaintDotNet.png

[TopIconLink]
    Measure=String
    String='explorer.exe "shell:appsFolder\dotPDNLLC.paint.net_h55e3w7q8jbva!dotPDNLLC.paint.net"'

[LeftIconImage]
    Measure=String
    String=Word.png

[LeftIconLink]
    Measure=String
    String="C:\Program Files\Microsoft Office\root\Office16\WinWord.exe"

[RightIconImage]
    Measure=String
    String=Excel.png

[RightIconLink]
    Measure=String
    String="C:\Program Files\Microsoft Office\root\Office16\Excel.exe"