[TopIconImage]
    Measure=String
    String=Chrome.png

[TopIconLink]
    Measure=String
    String="C:\Program Files (x86)\Google\Chrome\Application\Chrome.exe"

[LeftIconImage]
    Measure=String
    String=Firefox.png

[LeftIconLink]
    Measure=String
    String="C:\Program Files\Mozilla Firefox\firefox.exe"

[RightIconImage]
    Measure=String
    String=InternetExplorer.png

[RightIconLink]
    Measure=String
    String="C:\Program Files\internet explorer\iexplore.exe"